// NYC Midnight 500-Word Fiction Challenge 2026 — Round 1 assignments
// Scraped from https://www.nycmidnight.com/500fc/2026-1stroundassignments
// 3,456 writers across 86 groups

const GROUPS = [
  {id:1, genre:"Suspense and/or Thriller", action:"Fingerprinting", object:"A moped", writers:41, countries:{"United States":22,"Canada":8,"United Kingdom":5,"Australia":5,"Poland":1}},
  {id:2, genre:"Romantic Comedy", action:"Disagreeing", object:"A bus", writers:41, countries:{"United States":28,"United Kingdom":5,"Australia":4,"Canada":2,"Spain":1,"Austria":1}},
  {id:3, genre:"Horror", action:"Agreeing", object:"A dumbbell", writers:41, countries:{"United States":30,"United Kingdom":4,"Canada":4,"Ireland":2,"New Zealand":1}},
  {id:4, genre:"Sci-Fi", action:"Eloping", object:"A picnic table", writers:41, countries:{"United States":29,"Australia":4,"Canada":4,"New Zealand":2,"United Kingdom":1,"Netherlands":1}},
  {id:5, genre:"Drama", action:"Startling", object:"A fishing lure", writers:41, countries:{"United States":28,"United Kingdom":5,"Canada":2,"Germany":2,"Australia":2,"France":1,"Ireland":1}},
  {id:6, genre:"Suspense and/or Thriller", action:"Howling", object:"A wedding dress", writers:41, countries:{"United States":20,"United Kingdom":7,"Canada":5,"Australia":4,"Singapore":1,"Germany":1,"Ireland":1,"New Zealand":1,"France":1}},
  {id:7, genre:"Ghost Story", action:"Emptying a pocket", object:"A flashing light", writers:41, countries:{"United States":28,"United Kingdom":5,"Australia":5,"Canada":3}},
  {id:8, genre:"Ghost Story", action:"Romanticizing", object:"A painkiller", writers:41, countries:{"United States":31,"United Kingdom":6,"Canada":2,"Thailand":1,"Australia":1}},
  {id:9, genre:"Drama", action:"Delegating", object:"An olive", writers:41, countries:{"United States":28,"United Kingdom":7,"Australia":3,"Canada":2,"New Zealand":1}},
  {id:10, genre:"Comedy", action:"Letting one's hair down", object:"A baby carriage", writers:41, countries:{"United States":24,"Canada":6,"Australia":5,"United Kingdom":3,"Netherlands":1,"Switzerland":1,"Ireland":1}},
  {id:11, genre:"Historical Fiction", action:"Pulling an all-nighter", object:"A stepladder", writers:41, countries:{"United States":25,"Australia":5,"United Kingdom":5,"Germany":2,"Ireland":2,"Cayman Islands":1,"Costa Rica":1}},
  {id:12, genre:"Sci-Fi", action:"Hunting", object:"A safety belt", writers:41, countries:{"United States":26,"Australia":6,"Canada":4,"United Kingdom":3,"Ireland":1,"New Zealand":1}},
  {id:13, genre:"Historical Fiction", action:"Bandaging", object:"A teacup", writers:41, countries:{"United States":27,"Australia":6,"United Kingdom":4,"Canada":2,"Ireland":1,"Argentina":1}},
  {id:14, genre:"Ghost Story", action:"Taking a detour", object:"A chain", writers:41, countries:{"United States":28,"United Kingdom":7,"Canada":3,"Australia":2,"Ireland":1}},
  {id:15, genre:"Horror", action:"Eating cake", object:"A broom", writers:41, countries:{"United States":27,"Canada":5,"Ireland":3,"Australia":2,"United Kingdom":2,"France":1,"Japan":1}},
  {id:16, genre:"Horror", action:"Masquerading", object:"A fortune cookie", writers:41, countries:{"United States":28,"Canada":6,"Australia":3,"Ireland":2,"United Kingdom":1,"Germany":1}},
  {id:17, genre:"Ghost Story", action:"Photographing", object:"A doorbell", writers:41, countries:{"United States":25,"United Kingdom":9,"Canada":3,"Australia":2,"New Zealand":2}},
  {id:18, genre:"Comedy", action:"Demonstrating", object:"A brownie", writers:40, countries:{"United States":27,"Canada":5,"Australia":3,"United Kingdom":2,"Ireland":1,"Zambia":1,"South Africa":1}},
  {id:19, genre:"Fairy Tale and/or Fantasy", action:"Searching for food", object:"Mouthwash", writers:40, countries:{"United States":29,"Canada":5,"United Kingdom":3,"Australia":2,"Ireland":1}},
  {id:20, genre:"Romantic Comedy", action:"Telling a white lie", object:"A diamond", writers:40, countries:{"United States":26,"Canada":5,"Australia":5,"United Kingdom":3,"Ireland":1}},
  {id:21, genre:"Fairy Tale and/or Fantasy", action:"Expecting the worst", object:"A pocketknife", writers:40, countries:{"United States":28,"United Kingdom":4,"Canada":3,"Australia":4,"Zimbabwe":1}},
  {id:22, genre:"Comedy", action:"Cleaning a car", object:"A brochure", writers:40, countries:{"United States":26,"United Kingdom":4,"Canada":4,"Australia":3,"Ireland":2,"Vietnam":1}},
  {id:23, genre:"Romance", action:"Placing a wager", object:"Apple pie", writers:40, countries:{"United States":28,"Canada":7,"United Kingdom":2,"Ireland":1,"Poland":1,"Australia":1}},
  {id:24, genre:"Action and/or Adventure", action:"Searching for someone", object:"A sandwich", writers:40, countries:{"United States":28,"Canada":6,"United Kingdom":3,"Cambodia":1,"Australia":1,"Türkiye":1}},
  {id:25, genre:"Horror", action:"Serenading", object:"A bubble", writers:40, countries:{"United States":27,"Canada":6,"United Kingdom":2,"New Zealand":2,"Germany":1,"Japan":1,"Netherlands":1}},
  {id:26, genre:"Comedy", action:"Eating something sweet", object:"A briefcase", writers:40, countries:{"United States":23,"United Kingdom":7,"Canada":6,"Australia":1,"New Zealand":1,"Germany":1,"Switzerland":1}},
  {id:27, genre:"Drama", action:"Weeding", object:"A frying pan", writers:40, countries:{"United States":19,"United Kingdom":10,"Canada":4,"Australia":4,"New Zealand":2,"Portugal":1}},
  {id:28, genre:"Action and/or Adventure", action:"Blowing off steam", object:"A blindfold", writers:40, countries:{"United States":24,"Canada":6,"United Kingdom":4,"Australia":4,"Ireland":1,"Netherlands":1}},
  {id:29, genre:"Romance", action:"Freezing", object:"A teardrop", writers:40, countries:{"United States":23,"Canada":7,"United Kingdom":7,"Australia":2,"Turks and Caicos Islands":1}},
  {id:30, genre:"Suspense and/or Thriller", action:"Making popcorn", object:"A chimney", writers:40, countries:{"United States":29,"United Kingdom":5,"Australia":3,"Canada":2,"Ireland":1}},
  {id:31, genre:"Drama", action:"Getting scammed", object:"Chocolate milk", writers:40, countries:{"United States":33,"United Kingdom":3,"Canada":2,"Ireland":1,"Greece":1}},
  {id:32, genre:"Suspense and/or Thriller", action:"Disengaging", object:"A blender", writers:40, countries:{"United States":26,"Canada":6,"United Kingdom":5,"Australia":2,"New Zealand":1}},
  {id:33, genre:"Drama", action:"Memorizing", object:"Seaweed", writers:40, countries:{"United States":25,"Australia":5,"United Kingdom":4,"Canada":3,"Ireland":1,"New Zealand":1,"Italy":1}},
  {id:34, genre:"Fairy Tale and/or Fantasy", action:"Spilling the beans", object:"A postcard", writers:40, countries:{"United States":27,"Canada":5,"Australia":4,"United Kingdom":3,"Netherlands":1}},
  {id:35, genre:"Historical Fiction", action:"Setting a timer", object:"A recipe", writers:40, countries:{"United States":26,"United Kingdom":5,"Canada":4,"Australia":2,"Mexico":1,"New Zealand":1,"Italy":1}},
  {id:36, genre:"Comedy", action:"Browsing", object:"A ballot", writers:40, countries:{"United States":27,"United Kingdom":4,"Canada":3,"Australia":3,"Ireland":1,"Denmark":1,"Germany":1}},
  {id:37, genre:"Action and/or Adventure", action:"Shaving", object:"Firewood", writers:40, countries:{"United States":31,"United Kingdom":3,"Canada":2,"New Zealand":2,"Australia":1,"Ireland":1}},
  {id:38, genre:"Sci-Fi", action:"Descending", object:"A gumball", writers:40, countries:{"United States":28,"United Kingdom":4,"Canada":4,"Australia":3,"Luxembourg":1}},
  {id:39, genre:"Romance", action:"Ringing a doorbell", object:"A paper airplane", writers:40, countries:{"United States":31,"Australia":6,"United Kingdom":1,"Canada":1,"Spain":1}},
  {id:40, genre:"Action and/or Adventure", action:"Diving", object:"A campfire", writers:39, countries:{"United States":24,"United Kingdom":9,"Australia":5,"Canada":1}},
  {id:41, genre:"Historical Fiction", action:"Stubbing", object:"A blueberry", writers:40, countries:{"United States":30,"Canada":2,"United Kingdom":2,"Ireland":2,"Netherlands":2,"Australia":1,"Luxembourg":1}},
  {id:42, genre:"Romantic Comedy", action:"Walking a dog", object:"A trophy", writers:40, countries:{"United States":33,"Australia":3,"India":1,"Ireland":1,"Canada":1,"Denmark":1}},
  {id:43, genre:"Sci-Fi", action:"Predicting the future", object:"A bunk bed", writers:40, countries:{"United States":25,"Canada":5,"United Kingdom":4,"Australia":4,"Singapore":1,"Turks and Caicos Islands":1}},
  {id:44, genre:"Romantic Comedy", action:"Mansplaining", object:"A scarecrow", writers:40, countries:{"United States":26,"United Kingdom":5,"Canada":3,"Australia":3,"Ireland":1,"Greece":1,"Great Britain":1}},
  {id:45, genre:"Sci-Fi", action:"Quitting", object:"Pepper spray", writers:40, countries:{"United States":25,"Canada":9,"Australia":2,"United Kingdom":2,"Ireland":1,"France":1}},
  {id:46, genre:"Suspense and/or Thriller", action:"Setting off a firework", object:"Duct tape", writers:40, countries:{"United States":33,"United Kingdom":6,"Australia":1}},
  {id:47, genre:"Sci-Fi", action:"Getting fired from a job", object:"A bandage", writers:40, countries:{"United States":26,"Canada":6,"United Kingdom":4,"Australia":2,"Bulgaria":1,"India":1}},
  {id:48, genre:"Historical Fiction", action:"Tiptoeing", object:"An omelet", writers:40, countries:{"United States":22,"United Kingdom":9,"Canada":4,"Australia":3,"New Zealand":1,"Finland":1}},
  {id:49, genre:"Historical Fiction", action:"Ascending", object:"A clipboard", writers:40, countries:{"United States":24,"United Kingdom":4,"Canada":4,"Australia":4,"United Arab Emirates":1,"Spain":1,"Ireland":1,"New Zealand":1}},
  {id:50, genre:"Romance", action:"Sorting", object:"A cookbook", writers:40, countries:{"United States":28,"Canada":6,"United Kingdom":4,"Australia":1,"China":1}},
  {id:51, genre:"Comedy", action:"Cashing a check", object:"A birdhouse", writers:40, countries:{"United States":30,"Canada":4,"Australia":3,"United Kingdom":2,"Germany":1}},
  {id:52, genre:"Comedy", action:"Jumping into a pool", object:"Ravioli", writers:40, countries:{"United States":28,"Canada":5,"United Kingdom":4,"Australia":3}},
  {id:53, genre:"Action and/or Adventure", action:"A fist bump", object:"A seashell", writers:40, countries:{"United States":31,"United Kingdom":4,"Australia":3,"Canada":1,"Malaysia":1}},
  {id:54, genre:"Ghost Story", action:"Impressing", object:"An air pump", writers:40, countries:{"United States":22,"United Kingdom":6,"Canada":4,"Australia":2,"New Zealand":2,"Great Britain":1,"Ireland":1,"Thailand":1,"Italy":1}},
  {id:55, genre:"Fairy Tale and/or Fantasy", action:"Hunting for treasure", object:"A keychain", writers:40, countries:{"United States":22,"Australia":7,"United Kingdom":6,"Canada":2,"Spain":1,"Bolivia":1,"New Zealand":1}},
  {id:56, genre:"Horror", action:"Decorating", object:"An anchor", writers:40, countries:{"United States":24,"United Kingdom":6,"Canada":4,"Australia":4,"Netherlands":1,"Ireland":1}},
  {id:57, genre:"Fairy Tale and/or Fantasy", action:"Silencing", object:"A canoe", writers:40, countries:{"United States":25,"Canada":6,"United Kingdom":3,"Australia":2,"New Zealand":1,"Germany":1,"Ukraine":1,"Great Britain":1}},
  {id:58, genre:"Romantic Comedy", action:"Initiating", object:"Maple syrup", writers:40, countries:{"United States":31,"United Kingdom":4,"Germany":1,"Brazil":1,"Canada":1,"Virgin Islands (U.S.)":1,"Australia":1}},
  {id:59, genre:"Suspense and/or Thriller", action:"Fulfilling an obligation", object:"A washing machine", writers:40, countries:{"United States":27,"Australia":5,"United Kingdom":5,"Canada":3}},
  {id:60, genre:"Sci-Fi", action:"Running", object:"A banana", writers:40, countries:{"United States":26,"United Kingdom":6,"Canada":5,"Australia":2,"Switzerland":1}},
  {id:61, genre:"Romantic Comedy", action:"Getting hired for a job", object:"Poison", writers:40, countries:{"United States":27,"Australia":6,"Canada":2,"United Kingdom":3,"Ireland":1,"Netherlands":1}},
  {id:62, genre:"Drama", action:"Introducing", object:"A hamburger", writers:40, countries:{"United States":24,"United Kingdom":4,"Canada":4,"Australia":3,"Ireland":2,"Germany":1,"New Zealand":1,"Singapore":1}},
  {id:63, genre:"Suspense and/or Thriller", action:"Yelling", object:"A basket", writers:40, countries:{"United States":28,"United Kingdom":4,"Australia":4,"Canada":4}},
  {id:64, genre:"Sci-Fi", action:"Eating something spicy", object:"A footlocker", writers:40, countries:{"United States":32,"United Kingdom":3,"Australia":2,"Canada":1,"New Zealand":1,"Ireland":1}},
  {id:65, genre:"Suspense and/or Thriller", action:"Muting", object:"A lunch box", writers:40, countries:{"United States":24,"United Kingdom":6,"Australia":4,"Canada":3,"New Zealand":1,"Finland":1,"France":1}},
  {id:66, genre:"Horror", action:"Oscillating", object:"A spider", writers:40, countries:{"United States":27,"Australia":4,"Canada":4,"United Kingdom":2,"New Zealand":2,"Mexico":1}},
  {id:67, genre:"Horror", action:"Getting married", object:"A clothesline", writers:40, countries:{"United States":24,"Canada":6,"United Kingdom":4,"Australia":3,"Sweden":1,"Belgium":1,"New Zealand":1}},
  {id:68, genre:"Drama", action:"Jumping the gun", object:"A beard", writers:40, countries:{"United States":30,"Canada":4,"United Kingdom":4,"Australia":2}},
  {id:69, genre:"Romance", action:"Shielding", object:"A curler", writers:40, countries:{"United States":29,"United Kingdom":4,"Canada":3,"Australia":3,"New Zealand":1}},
  {id:70, genre:"Romance", action:"Investigating", object:"A shoebox", writers:40, countries:{"United States":28,"United Kingdom":4,"Australia":3,"Canada":2,"New Zealand":1,"Ireland":1,"Great Britain":1}},
  {id:71, genre:"Comedy", action:"Giving directions", object:"A bonfire", writers:40, countries:{"United States":26,"United Kingdom":5,"Australia":4,"Canada":2,"Luxembourg":1,"Spain":1,"Romania":1}},
  {id:72, genre:"Ghost Story", action:"Going on a first date", object:"A bathing suit", writers:40, countries:{"United States":27,"Canada":4,"Australia":3,"United Kingdom":2,"Norway":1,"New Zealand":1,"Ireland":1,"India":1}},
  {id:73, genre:"Romantic Comedy", action:"Smearing", object:"A hoodie", writers:40, countries:{"United States":25,"Australia":5,"Canada":4,"United Kingdom":3,"Ireland":2,"Mexico":1}},
  {id:74, genre:"Action and/or Adventure", action:"Eating something sour", object:"A solar panel", writers:40, countries:{"United States":29,"Australia":4,"Canada":3,"United Kingdom":3,"Portugal":1}},
  {id:75, genre:"Action and/or Adventure", action:"Picking up the pace", object:"Coffee", writers:40, countries:{"United States":24,"United Kingdom":9,"Canada":3,"Australia":3,"Great Britain":1}},
  {id:76, genre:"Romantic Comedy", action:"Grasping at straws", object:"A wallet", writers:40, countries:{"United States":25,"Australia":6,"United Kingdom":4,"Canada":4,"New Zealand":1}},
  {id:77, genre:"Romance", action:"Social distancing", object:"A clover", writers:40, countries:{"United States":28,"Australia":4,"Canada":3,"United Kingdom":2,"New Zealand":2,"Colombia":1}},
  {id:78, genre:"Ghost Story", action:"Turning on a light", object:"A fire extinguisher", writers:40, countries:{"United States":26,"Australia":7,"United Kingdom":4,"New Zealand":2,"Great Britain":1}},
  {id:79, genre:"Fairy Tale and/or Fantasy", action:"Squirming", object:"A ribbon", writers:40, countries:{"United States":24,"United Kingdom":6,"Australia":5,"Ireland":3,"Canada":2}},
  {id:80, genre:"Horror", action:"Daydreaming", object:"Goggles", writers:40, countries:{"United States":23,"United Kingdom":7,"Australia":4,"Canada":4,"South Africa":1,"New Zealand":1}},
  {id:81, genre:"Drama", action:"Deleting", object:"A cookie", writers:40, countries:{"United States":31,"Australia":3,"Canada":2,"Ireland":2,"United Kingdom":1,"Luxembourg":1}},
  {id:82, genre:"Fairy Tale and/or Fantasy", action:"Letting go", object:"Lemonade", writers:40, countries:{"United States":29,"Australia":4,"Canada":3,"United Kingdom":2,"Denmark":1,"Great Britain":1}},
  {id:83, genre:"Fairy Tale and/or Fantasy", action:"Sighing", object:"A rocking chair", writers:40, countries:{"United States":23,"Canada":11,"Australia":3,"United Kingdom":3}},
  {id:84, genre:"Romance", action:"Hiking", object:"A souvenir", writers:40, countries:{"United States":25,"Canada":6,"Australia":5,"United Kingdom":2,"New Zealand":1,"Ireland":1}},
  {id:85, genre:"Ghost Story", action:"Bouncing", object:"A microwave", writers:40, countries:{"United States":24,"Canada":5,"Australia":4,"United Kingdom":3,"Netherlands":1,"Puerto Rico":1,"Thailand":1,"Singapore":1}},
  {id:86, genre:"Historical Fiction", action:"Unwrapping", object:"A dinghy", writers:40, countries:{"United States":31,"United Kingdom":4,"Canada":4,"Australia":1}}
];

// Object semantic categories
const OBJECT_THEMES = {
  "Food & Drink": [9,16,18,23,24,31,33,38,41,48,52,58,60,62,75,81,82],
  "Vehicles": [1,2,10,57,86],
  "Household & Appliances": [15,17,27,30,32,59,67,85],
  "Containers": [26,63,64,65,70,76],
  "Clothing & Wearables": [6,28,72,73,80],
  "Tools & Implements": [3,5,11,14,21,46,54],
  "Paper & Documents": [22,34,35,36,49,50],
  "Body & Personal Care": [19,29,68,69],
  "Nature & Outdoors": [37,40,51,53,71,77],
  "Safety & Medical": [8,12,45,47,78],
  "Symbolic & Decorative": [20,42,43,44,55,79,84],
  "Light & Ephemeral": [7,25,39],
  "Animals": [66],
  "Furniture": [4,83],
  "Tech & Industrial": [56,61,74],
};

// Action semantic categories
const ACTION_THEMES = {
  "Movement": [14,38,40,42,48,49,52,60,66,75,79,84,85],
  "Eating & Cooking": [15,26,30,64,74],
  "Communication": [2,3,44,71],
  "Emotion & Vibe": [8,10,21,28,82,83],
  "Social & Romance": [4,39,53,54,58,62,67,72],
  "Pursuit & Search": [12,19,24,55,70],
  "Deception & Secrets": [16,20,31,34],
  "Performance & Display": [17,18,25,56],
  "Mental & Internal": [33,43,80],
  "Work & Money": [9,11,47,51,61],
  "Separation & End": [32,45,77,81],
  "Control & Silence": [57,65,69],
  "Vocal": [6,63],
  "Chore & Repair": [13,22,27,37],
  "Surprise & Chaos": [5,46,68],
  "Other": [1,7,29,35,36,41,46,50,73,78,86,76],
};

// Genre color palette
const GENRE_COLORS = {
  "Suspense and/or Thriller": "#5b2a86",
  "Romantic Comedy": "#ff6f91",
  "Horror": "#1a1a1a",
  "Sci-Fi": "#1f78b4",
  "Drama": "#e07a3a",
  "Ghost Story": "#6a8d92",
  "Comedy": "#ffb347",
  "Historical Fiction": "#8b5a2b",
  "Fairy Tale and/or Fantasy": "#9b59b6",
  "Romance": "#e74c3c",
  "Action and/or Adventure": "#27ae60",
};

// Publishing sample (50 writers, deterministic sample of every 69th from the 3,456-row Airtable)
// Researched via web search of names + locations. Bucket key:
//  TRAD_PUB   — traditional publisher (named press, agent, multiple titles)
//  INDIE_PUB  — self/indie books with traceable Amazon/Goodreads presence
//  SHORT_PUB  — published short fiction/poetry/reviews; no books
//  HOBBYIST   — Stage32/Substack/blog presence, no curated publication
//  UNCLEAR    — common name, can't disambiguate
//  NONE       — no writing-related findings online
const PUBLISHING_SAMPLE = [
  {name:"Aurora Akinpeloye", loc:"Grand Blanc, USA", bucket:"NONE", note:"no writing presence found"},
  {name:"Zachary Arama", loc:"Maple Valley, USA", bucket:"SHORT_PUB", note:"flash fiction at Fiction Attic Press; personal author site"},
  {name:"Shaun Baland", loc:"Mesa, USA", bucket:"HOBBYIST", note:"Stage 32 screenwriter profile; film reviews"},
  {name:"Phillip Bell", loc:"Frankston, AU", bucket:"UNCLEAR", note:"multiple Australian Phillip Bells, no Frankston fiction match"},
  {name:"Emily Bliss", loc:"Holden, USA", bucket:"NONE", note:"mental health counselor; children's book Emily Bliss is a different person"},
  {name:"Spencer Brinker", loc:"Lakeville, USA", bucket:"TRAD_PUB", note:"69+ children's books with Bearport Publishing (also Director there)"},
  {name:"Sherri Byrand", loc:"Los Angeles, USA", bucket:"NONE", note:"no writing presence found"},
  {name:"Casey Cavolaski", loc:"Mesa, USA", bucket:"NONE", note:"no writing presence found"},
  {name:"Georgia Clinton", loc:"Farmers Branch, USA", bucket:"NONE", note:"no writing presence found"},
  {name:"Chance Cougar", loc:"West Burlington, USA", bucket:"NONE", note:"no writing presence found"},
  {name:"S.E. Daniels", loc:"Camden, USA", bucket:"UNCLEAR", note:"common name, no Camden match"},
  {name:"Amanda Dew", loc:"Ipswich, UK", bucket:"INDIE_PUB", note:"The Seer indie YA trilogy on Amazon (2021–2022)"},
  {name:"Tracy Dunstan", loc:"Argyle, Canada", bucket:"UNCLEAR", note:"NY-based Tracy Nicole Dunstan published with Arcadia but not the Canadian match"},
  {name:"Constance Evelyn", loc:"Ottawa, Canada", bucket:"NONE", note:"no Ottawa writer match"},
  {name:"M. M. Fonseca", loc:"Boston, USA", bucket:"NONE", note:"no writer match for this name"},
  {name:"TR Garcia", loc:"Inman, USA", bucket:"NONE", note:"no match found"},
  {name:"Josh Goller", loc:"Oak Grove, USA", bucket:"SHORT_PUB", note:"editor of The Molotov Cocktail flash zine; many lit-mag bylines (Portland match is plausible)"},
  {name:"Amy Grinna", loc:"Decorah, USA", bucket:"NONE", note:"Decorah resident on food-co-op board; no writing credits"},
  {name:"Laura Harbin", loc:"Toronto, Canada", bucket:"TRAD_PUB", note:"TV writer/producer; episodes of The Next Step & Lost & Found (screen, not prose)"},
  {name:"Amanda Henke", loc:"Minneapolis, USA", bucket:"TRAD_PUB", note:"children's picture book Not A Book About Bunnies (Starry Forest, 2023); Hamline MFA"},
  {name:"RJG Hougham", loc:"Bournemouth, UK", bucket:"SHORT_PUB", note:"active writer persona; claims a 2020 debut, unverified"},
  {name:"Richard Jackson", loc:"Yateley, UK", bucket:"UNCLEAR", note:"name overlaps with S&S editor, poet, academic"},
  {name:"Romilly Jones", loc:"London, UK", bucket:"NONE", note:"no author/poet match"},
  {name:"Molly Kelly", loc:"Cork, Ireland", bucket:"UNCLEAR", note:"common name; dominated by other Irish writers"},
  {name:"E. H. Knightly", loc:"Calgary, Canada", bucket:"NONE", note:"no Calgary author match"},
  {name:"Meaghan Lane", loc:"Spokane, USA", bucket:"NONE", note:"no Spokane writer match"},
  {name:"Margo Lemberger", loc:"New York City, USA", bucket:"SHORT_PUB", note:"bylines in Jewish Forward, Arts Indiana, NUVO; WritersWeekly 24h contest winner 2024"},
  {name:"Cat Love", loc:"Newark, USA", bucket:"NONE", note:"only unrelated books titled 'Cat Love' surface"},
  {name:"Robert Mancer", loc:"San José, USA", bucket:"NONE", note:"no published writer match"},
  {name:"Jennifer Maveety", loc:"Ashland, USA", bucket:"SHORT_PUB", note:"book reviewer for Foreword Reviews; no original works"},
  {name:"Shanna McNair", loc:"Topsham, USA", bucket:"TRAD_PUB", note:"debut novel Soul Retrieval (High Frequency Press, 2025); founded The Writer's Hotel"},
  {name:"Laila Miller", loc:"Perth, AU", bucket:"UNCLEAR", note:"possible match to children's writer but name doesn't quite line up"},
  {name:"Adam Motz", loc:"Chicago, USA", bucket:"INDIE_PUB", note:"children's book You Come From Love (Gatekeeper Press); attorney/writer"},
  {name:"Pran Nibber", loc:"Calgary, Canada", bucket:"NONE", note:"medical advisor with health-industry bylines, no fiction"},
  {name:"Lombard Olivier", loc:"Youngsville, USA", bucket:"NONE", note:"no author results"},
  {name:"Nicholas G Patides", loc:"Tampa, USA", bucket:"NONE", note:"no writing-related results"},
  {name:"Stephen Polk", loc:"Nanaimo, Canada", bucket:"UNCLEAR", note:"Stephen T. Polk SFF blog exists; Nanaimo link unconfirmed"},
  {name:"R.C. Ranger", loc:"Lexington, USA", bucket:"NONE", note:"results dominated by Ranger's Apprentice series, no R.C. Ranger"},
  {name:"Edouard Riviera", loc:"Oviedo, USA", bucket:"NONE", note:"no writing results in Oviedo FL"},
  {name:"Russell Rudzinski", loc:"Fayetteville, USA", bucket:"UNCLEAR", note:"UArk architecture prof; namesake wrote 1969 Japanese cookbook"},
  {name:"Emily Sayers", loc:"Richmond, USA", bucket:"UNCLEAR", note:"only Goodreads reader profile and unrelated namesakes"},
  {name:"Melina Shaughnessy", loc:"St Albans, UK", bucket:"UNCLEAR", note:"Goodreads reader profile, no authored works found"},
  {name:"Wendell Smith", loc:"Bell Buckle, USA", bucket:"UNCLEAR", note:"name dominated by historic Pittsburgh Courier sportswriter"},
  {name:"Elizabeth Stewart", loc:"Gibsonia, USA", bucket:"UNCLEAR", note:"multiple published Elizabeth Stewarts, none in Gibsonia PA"},
  {name:"Carmen Tadich", loc:"Eastend, Canada", bucket:"NONE", note:"not in Saskatchewan Writers' Guild listings"},
  {name:"Sierra Tofelt", loc:"Sacramento, USA", bucket:"TRAD_PUB", note:"Stone Soup, Scholastic Art & Writing Awards, 20+ youth poetry awards"},
  {name:"Gerhardus van Wilgen", loc:"Voorhees, USA", bucket:"SHORT_PUB", note:"playwright (MA theatre), Dramatists Guild, HowlRound essays"},
  {name:"Megan Warren", loc:"Austin, USA", bucket:"INDIE_PUB", note:"self-pub audio fiction podcast The Curse of Botley's Hedge"},
  {name:"John William", loc:"Hayes, UK", bucket:"UNCLEAR", note:"name too common, no disambiguating findings"},
  {name:"Marianne Xenos", loc:"Amherst, USA", bucket:"TRAD_PUB", note:"Writers of the Future Q4 2022 first place; Typehouse, Orion's Belt, anthology bylines"},
];

const PUB_BUCKETS = {
  TRAD_PUB: {label: "Traditionally published", color: "#a8d99c", desc: "Books with named publishers, agents, or multiple titles. Picture books, novels, screen credits."},
  INDIE_PUB: {label: "Indie / self-published", color: "#9bb1ff", desc: "Self-pub or hybrid press books on Amazon / Goodreads. Often a single title."},
  SHORT_PUB: {label: "Short-form published", color: "#e7c069", desc: "Lit-mag bylines, contest wins, dramaturgy, criticism — no books."},
  HOBBYIST: {label: "Hobbyist / amateur", color: "#c89a6c", desc: "Stage32, Substack, blog, Wattpad — public but uncurated."},
  UNCLEAR: {label: "Unclear (common name)", color: "#6b7480", desc: "Name too common to disambiguate from web search alone."},
  NONE: {label: "No findings", color: "#e08a99", desc: "No writing-related results online — likely unpublished entrants."},
};

// Prior 500FC finalists (top 10 + Honorable Mentions) — 2023, 2024, 2025
// Used as a watchlist + sanity check against the 2026 roster.
const PRIOR_FINALISTS = [
  // 2025
  {year: 2025, place: "#1", name: "Chloe Paige", loc: "Geelong, AU", story: "'Roo Sprayers"},
  {year: 2025, place: "#2", name: "Autumn Bettinger", loc: "—", story: "Simmering"},
  {year: 2025, place: "#3", name: "Miranda Lee", loc: "—", story: "I Am"},
  {year: 2025, place: "#4", name: "Ben Kaestner-Frenchman", loc: "—", story: "The Lost God of Aldo da Costa"},
  {year: 2025, place: "#5", name: "Ben Daggers", loc: "—", story: "This Rectangle"},
  {year: 2025, place: "#6", name: "Charlotte Racioppo", loc: "—", story: "Inheritance in Green and Yellow"},
  {year: 2025, place: "#7", name: "Acadia Hansen", loc: "Athens, OH", story: "Olive Oil"},
  {year: 2025, place: "#8", name: "John Curtis Bigelow", loc: "—", story: "Stormproof"},
  {year: 2025, place: "#9", name: "Elizabeth Hakken Candido", loc: "—", story: "These Sins Will Eat You Alive"},
  {year: 2025, place: "#10", name: "Victoria Dyson", loc: "—", story: "Zambian Heat and Blood"},
  {year: 2025, place: "HM", name: "Monica Mukerjee", loc: "—", story: "The Magpie"},
  {year: 2025, place: "HM", name: "Zoe Rose", loc: "—", story: "The Bone Keeper"},
  {year: 2025, place: "HM", name: "Avery Other", loc: "—", story: "A Sour Feast of Fears"},
  {year: 2025, place: "HM", name: "Liz Eyding", loc: "—", story: "Your Mother's Daughter"},
  {year: 2025, place: "HM", name: "Debbie Voetberg", loc: "—", story: "Chance of a Lifetime"},
  // 2024
  {year: 2024, place: "#1", name: "S.C. Mills", loc: "Seattle, WA", story: "Watchmaker's Hands"},
  {year: 2024, place: "#2", name: "Rachel Harbaugh", loc: "—", story: "When The Blue Smoke Drowns"},
  {year: 2024, place: "#3", name: "Melissa Jornd", loc: "—", story: "Tomorrow, Today"},
  {year: 2024, place: "#4", name: "Elysia Rourke", loc: "—", story: "Men Don't Hear Crops These Days"},
  {year: 2024, place: "#5", name: "Sally Demarest", loc: "—", story: "All the Ways to Die in Yellowstone"},
  {year: 2024, place: "#6", name: "Sarah Cousins", loc: "—", story: "To Feel the Night"},
  {year: 2024, place: "#7", name: "Myra Scott", loc: "—", story: "Elijah²"},
  {year: 2024, place: "#8", name: "Julian Shen", loc: "—", story: "Foreign Soil"},
  {year: 2024, place: "#9", name: "Beret Olsen", loc: "—", story: "The Tower, Old Milwaukee, and the Stars"},
  {year: 2024, place: "#10", name: "Lauren Sullivan", loc: "—", story: "Parallels"},
  {year: 2024, place: "HM", name: "Kristi Schirtzinger", loc: "—", story: "The Collector"},
  {year: 2024, place: "HM", name: "Erin West", loc: "—", story: "When Your Dog Dies"},
  {year: 2024, place: "HM", name: "JA Logwood", loc: "—", story: "Gift of the Kraken"},
  {year: 2024, place: "HM", name: "Chase Davis", loc: "—", story: "Lessons from a Drowning Star Chart"},
  {year: 2024, place: "HM", name: "Dylan Archer", loc: "—", story: "Doubles"},
  {year: 2024, place: "HM", name: "T. Kogan", loc: "—", story: "For Dad: In Three Acts"},
  {year: 2024, place: "HM", name: "Kenton Smalley", loc: "—", story: "Don't call us what we are"},
  {year: 2024, place: "HM", name: "Evan O'Cuana", loc: "—", story: "We Will Always Be Back Then"},
  {year: 2024, place: "HM", name: "Lior Forest", loc: "—", story: "Constellations Not Included"},
  {year: 2024, place: "HM", name: "Zelda C. Thorne", loc: "—", story: "Under my Skin"},
  // 2023
  {year: 2023, place: "#1", name: "Leila Murton Poole", loc: "London, UK", story: "Daddy, Are You In The Ground Or In The Sky?"},
  {year: 2023, place: "#2", name: "Josephine Queen", loc: "—", story: "Instructions on How to Grieve"},
  {year: 2023, place: "#3", name: "Harry Cunningham", loc: "—", story: "Don't Skewer the Messenger"},
  {year: 2023, place: "#4", name: "Alexandra Otto", loc: "—", story: "A Series of Real World Problems in Mathematics"},
  {year: 2023, place: "#5", name: "Jennifer Gunner", loc: "—", story: "Regret To Inform You"},
  {year: 2023, place: "#6", name: "Kirk Lee", loc: "—", story: "Nokotta"},
  {year: 2023, place: "#7", name: "Scott Russell", loc: "—", story: "Give the Devil His Due"},
  {year: 2023, place: "#8", name: "Lottie Green", loc: "—", story: "Earl Grey with the Reaper"},
  {year: 2023, place: "#9", name: "Laura J. Rayne", loc: "—", story: "Everything I Needed"},
  {year: 2023, place: "#10", name: "Laurie Swinarton", loc: "—", story: "I'm the Tag on Your Mattress"},
  {year: 2023, place: "HM", name: "Rocquel Motta", loc: "—", story: "The In Between"},
  {year: 2023, place: "HM", name: "Avery Other", loc: "—", story: "Eventually"},
  {year: 2023, place: "HM", name: "Dana Bentley", loc: "—", story: "The Golden Hour"},
  {year: 2023, place: "HM", name: "Zelda C. Thorne", loc: "—", story: "Let there be Darkness"},
  {year: 2023, place: "HM", name: "Bryn Takashiba", loc: "—", story: "The Inksmith"},
  {year: 2023, place: "HM", name: "Michael Capbarat", loc: "—", story: "Alive In Salem Woods"},
  {year: 2023, place: "HM", name: "Alison Schiller", loc: "—", story: "Hope & Other Ailments"},
  {year: 2023, place: "HM", name: "Nathaniel Chaney", loc: "—", story: "Safety First"},
  {year: 2023, place: "HM", name: "Asher Garcia", loc: "—", story: "Nerve Damage"},
  {year: 2023, place: "HM", name: "Indigo LaRue", loc: "—", story: "My Nana's Magic"},
];

// Compete data — three Garske groups with researched competitor profiles
// Buckets: TRAD_PUB / INDIE_PUB / SHORT_PUB / NYCM_VET / HOBBYIST / UNCLEAR / NONE
const COMPETE = {
  benton: {
    name: "Benton Garske",
    loc: "Maple Grove, MN",
    group: 53,
    prompt: {genre: "Action and/or Adventure", action: "A fist bump", object: "A seashell"},
    summary: "Light field. No prior 500FC finalists, only 3 competitors with traceable book-length publishing. Top-10 cutoff looks achievable with a solid action-adventure execution.",
    tier1: [], // no confirmed prior finalists
    tier2: [
      {name: "Noor Amjad", loc: "Calgary, Canada", bucket: "INDIE_PUB", note: "Self-pub action/fantasy novel 'The Unfolding' (2023). Genre is literally in her wheelhouse — top threat for an A/A prompt."},
      {name: "Adam Motz", loc: "Chicago, IL", bucket: "INDIE_PUB", note: "Children's book 'You Come From Love' (Gatekeeper Press); attorney/writer. Disciplined craft but kids-book voice differs from adult action."},
      {name: "Jim Furry", loc: "Conway, SC", bucket: "INDIE_PUB", note: "Retired FBI agent, 2 indie books, SWA short-story first-place winner. Genuine short-form competition pedigree + FBI background = dark horse for A/A."},
    ],
    tier3: [
      {name: "Christa Okon", loc: "Albuquerque, NM", bucket: "INDIE_PUB", note: "Indie memoir (Nazi to Empath) + children's book; intense lived experience."},
      {name: "Howard Comen", loc: "Charleston, SC", bucket: "UNCLEAR", note: "Retired PI with 40 years of operational stories; developing fiction series, raw material on-genre."},
    ],
    roster: [
      "Remus A | Kuala Lumpur, Malaysia",
      "Noor Amjad | Calgary, Canada",
      "Ruthy Bell | Winston Salem, NC",
      "Jennifer Beroshi | London, UK",
      "Ally Brooks | Burlington, NC",
      "Sian Brossard | Perth Amboy, NJ",
      "Anne Carrillo | Houston, TX",
      "Howard Comen | Charleston, SC",
      "Jane Connors | Sydney, Australia",
      "Kathryn Cook | Sydney, Australia",
      "Dusty Crocker | Flower Mound, TX",
      "Rebekah Diaz | Fort Worth, TX",
      "Brian Dobbs | Whitestown, IN",
      "Jim Furry | Conway, SC",
      "Benton Garske | Maple Grove, MN",
      "Lesley Grossblatt | Carson City, NV",
      "Michael Hudgins | Midland, TX",
      "Adriana Isaza | Shelburne Falls, MA",
      "Emma Johnson | Norwich, UK",
      "D Kestowers | Virginia Beach, VA",
      "Kelly Lawson | Maple Glen, PA",
      "Kit Liechtensteinflag | Verona, WI",
      "Helena Martin | Newton, NC",
      "Mila McCurrach | Jupiter, FL",
      "Cameron Medlin | Niles, MI",
      "Adam Motz | Chicago, IL",
      "D. Murphy | Cleveland, OH",
      "Christa Okon | Albuquerque, NM",
      "Dabi Olu-Odugbemi | London, UK",
      "Mette Ovringmo | Longmont, CO",
      "M Palla | Tinton Falls, NJ",
      "Andrea Partsafas | Medford, OR",
      "Hollie Pearce | Cairns, Australia",
      "Jenna Piotrzkowski | Fond du Lac, WI",
      "J. Ragland | Los Angeles, CA",
      "Stephen Robinson | Oxted, UK",
      "Shelly Romine | Clarkston, WA",
      "Randi Rossman | Austell, GA",
      "Adele Vogt | Salisbury, MD",
      "Kirstin Yu | Chicago, IL",
    ],
  },
  tom: {
    name: "Tom Garske",
    loc: "Denver, CO",
    group: 56,
    prompt: {genre: "Horror", action: "Decorating", object: "An anchor"},
    summary: "Heaviest competition of the three groups. Two confirmed NYCM medalists (Schreier, Jizba) plus a serious litmag writer (Nedelka) and a near-Penguin novelist (Rhodes). No prior 500FC finalists, but MM Schreier has podium finishes in harder NYCM formats.",
    tier1: [
      {name: "MM Schreier", loc: '"Chilly by the Sea, Imagination"', bucket: "NYCM_VET", note: "NYCM Short Story 2nd (2024), Flash Fiction 3rd (2025) + 10th (2022); two short-story collections (Monstrosity, Humanity / Bruised, Resilient); pubs in Flash Fiction Online. The whimsical entry location matches her published bio verbatim. THE one to beat."},
      {name: "Susan Eileen Jizba", loc: "Los Angeles, CA", bucket: "NYCM_VET", note: "Multi-year NYCM veteran: top-15 in FFC 2022, top-15 Short Screenplay 2022, HMs in FFC/250/100, 4th in 100-word microfiction R1, 79+ FilmFreeway awards. Knows the NYCM judging mindset."},
    ],
    tier2: [
      {name: "Shannon CC Nedelka", loc: "Dover, NH", bucket: "SHORT_PUB", note: "Physician + fiction writer; flash piece 'Trauma' in West Trade Review (Mar 2023); Grub Street trained. Litmag craft without proven NYCM track record."},
      {name: "Rhonda Rhodes", loc: "Houston, TX", bucket: "INDIE_PUB", note: "Novelist 'Almost Magic' won WGT Manuscript Contest, secured agent, near-Penguin/Berkley deal; owns The Lift bookstore. Novelist craft — less proven on short form."},
      {name: "Zachary Arama", loc: "Maple Valley, WA", bucket: "SHORT_PUB", note: "Flash fiction at Fiction Attic Press; personal author site."},
    ],
    tier3: [
      {name: "Simon Boudreau", loc: "Montréal, Canada", bucket: "UNCLEAR", note: "A Simon Boudreault (spelling differs) is a Montréal playwright + BMO Dramatic Author Prize 2014 winner — possible same person."},
    ],
    roster: [
      "Chaos - | Netherlands",
      "Zachary Arama | Maple Valley, WA",
      "Jordan Beck | Milwaukee, WI",
      "Simon Boudreau | Montréal, Canada",
      "Rob Bremer | Lacombe, LA",
      "Stephanie Chatt | Calgary, Canada",
      "Allison Clark | Antelope, CA",
      "Noah Clinton | Manorcunningham, Ireland",
      "Cassiel Code | Cambridge, UK",
      "James Curran | Maspeth, NY",
      "Courtney Evans | Beachlands, Australia",
      "Tom Garske | Denver, CO",
      "AJ George | London, UK",
      "Nicole Green | Oakland, CA",
      "Anthony Hawkins | London, UK",
      "Kenny Hicks | Denver, CO",
      "Susan Eileen Jizba | Los Angeles, CA",
      "Haych Lachapelle | Seattle, WA",
      "Tash Ledger | Margaret River, Australia",
      "Evangeline Lee | Tucson, AZ",
      "Brittany Marlatt | Calgary, Canada",
      "Sara Myers | Belleville, IL",
      "Jaime Nabrynski | Goodlettsville, TN",
      "Shannon CC Nedelka | Dover, NH",
      "Abby Olsen | Jamul, CA",
      "Larry Padgett | La Habra Hgts, CA",
      "Alexander Price | Cardiff, UK",
      "Phillip Register | Durham, NC",
      "Rhonda Rhodes | Houston, TX",
      "David Roe | Mahone Bay, Canada",
      "Bruce Rose | Great Barrington, MA",
      "Deborah Rose | Coseley, UK",
      "MM Schreier | Chilly by the Sea, Imagination",
      "Glenda Scott | Stoneville, Australia",
      "Michael Seckman | Houston, TX",
      "Lynn St.Bernard | Millersville, MD",
      "Jeannine Ugalde | Thousand Oaks, CA",
      "Isabella vigier rathor | Manchester, UK",
      "Tamara Yarnold | Brisbane, Australia",
      "Ami Zelkova | Aberdeen, WA",
    ],
  },
  valerie: {
    name: "Valerie Garske",
    loc: "Mesa, AZ",
    group: 84,
    prompt: {genre: "Romance", action: "Hiking", object: "A souvenir"},
    summary: "ONE confirmed prior 500FC finalist (Acadia Hansen, #7 in 2025) plus three credentialed competitors. Acadia is the slot-1 contender. Of 10 advancing slots, ~4 are likely spoken for by veterans — Valerie's real fight is for slots 5–10.",
    tier1: [
      {name: "Acadia Hansen", loc: "Athens, OH", bucket: "NYCM_VET", note: "★ CONFIRMED 2025 500FC #7 FINALIST (story 'Olive Oil'). Already cleared every round to the top tier last year. Plan around her."},
    ],
    tier2: [
      {name: "Alexandria Bellani", loc: "Canberra, Australia", bucket: "NYCM_VET", note: "Prior 500FC entrant — story 'The God of Giving Up' featured on nycmidnight.com; 2nd place Not Quite Write Prize Jan 2025; pub in Elegant Literature; forthcoming Rat Bag Lit. Active short-fiction competitor."},
      {name: "Steph Coelho", loc: "Montreal, Canada", bucket: "SHORT_PUB", note: "Professional writer/editor; Book Riot contributor; bylines at Washington Post + Healthline; runs writing prompt newsletter; documented NYCM community involvement (Flash Fiction Master List)."},
      {name: "Ralph Greco Jr.", loc: "Ligonier, PA", bucket: "TRAD_PUB", note: "Internationally published short-story author across 8 countries; collections via Scimitar Edge (UK), Audible; anthology contributions. Veteran of the short-fiction submission grind."},
    ],
    tier3: [
      {name: "Leigh Clements", loc: "Toronto, Canada", bucket: "INDIE_PUB", note: "Founder of Shot In The Dark Mysteries; commercial mystery writer + serialized novels — game/script craft, less literary."},
    ],
    roster: [
      "Michael Arden | Covington, KY",
      "Madelaine Beevers | London, UK",
      "Alexandria Bellani | Canberra, Australia",
      "Michael Bevan | Tofield, Canada",
      "Hayley Brooke | Franklin Lakes, NJ",
      "Madalina Capra | Westland, MI",
      "Leigh Clements | Toronto, Canada",
      "Steph Coelho | Montreal, Canada",
      "Orion Fang | Fremont, CA",
      "Valerie Garske | Mesa, AZ",
      "Beth Garvey | Christchurch, New Zealand",
      "Ralph Greco | Ligonier, PA",
      "Alleul Greene | Houston, TX",
      "Acadia Hansen | Athens, OH",
      "Erin Hilton | Hobart, Australia",
      "Ella Hynes | Calgary, Canada",
      "Richard Jaramillo | Taylorsville, UT",
      "Amy Johnson | San Francisco, CA",
      "Romilly Jones | London, UK",
      "Kirsten Kaiser | Harrington Park, NJ",
      "M. Kelleher | New Orleans, LA",
      "Sophia Leigh | Decatur, GA",
      "Aro Levi | Brisbane, Australia",
      "Ian Long | Lancaster, PA",
      "Maree Lucks | Melbourne, Australia",
      "Kendal M | Belleville, IL",
      "Elizabeth Marrero | Little Rock, AR",
      "Brandi Miller | Nashville, TN",
      "Maverick Monroe | Brooklyn, NY",
      "Sean Ness | Canberra, Australia",
      "Nickolis Parker | Belton, TX",
      "Stephen Polk | Nanaimo, Canada",
      "Rachel Quinlan | Athenry, Ireland",
      "Lakshmi Rasa | Chicago, IL",
      "Camille Rodriguez | San Jose, CA",
      "Anita T | Mississauga, Canada",
      "Ben Thom | Romeoville, IL",
      "Shane Tilston | Brooklyn, NY",
      "Garrett Vargas | Seattle, WA",
      "Thomas Ware | Arlington, VA",
    ],
  },
};

// Continent mapping for region rollup
const CONTINENT = {
  "United States":"North America","Canada":"North America","Mexico":"North America",
  "Puerto Rico":"North America","Cayman Islands":"North America","Turks and Caicos Islands":"North America","Virgin Islands (U.S.)":"North America",
  "United Kingdom":"Europe","Great Britain":"Europe","Ireland":"Europe","Germany":"Europe","France":"Europe","Spain":"Europe","Italy":"Europe","Portugal":"Europe","Netherlands":"Europe","Belgium":"Europe","Switzerland":"Europe","Austria":"Europe","Denmark":"Europe","Finland":"Europe","Norway":"Europe","Sweden":"Europe","Poland":"Europe","Greece":"Europe","Bulgaria":"Europe","Luxembourg":"Europe","Romania":"Europe","Ukraine":"Europe","Türkiye":"Europe",
  "Australia":"Oceania","New Zealand":"Oceania",
  "Singapore":"Asia","Japan":"Asia","India":"Asia","Thailand":"Asia","Malaysia":"Asia","China":"Asia","Cambodia":"Asia","Vietnam":"Asia","United Arab Emirates":"Asia",
  "South Africa":"Africa","Zambia":"Africa","Zimbabwe":"Africa",
  "Brazil":"South America","Argentina":"South America","Bolivia":"South America","Colombia":"South America","Costa Rica":"North America",
};
